// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: registry/v1/registry.proto

package registryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProtocolRegistry_PublishProtocol_FullMethodName      = "/registry.v1.ProtocolRegistry/PublishProtocol"
	ProtocolRegistry_GetProtocol_FullMethodName          = "/registry.v1.ProtocolRegistry/GetProtocol"
	ProtocolRegistry_RegisterConsumer_FullMethodName     = "/registry.v1.ProtocolRegistry/RegisterConsumer"
	ProtocolRegistry_UnregisterConsumer_FullMethodName   = "/registry.v1.ProtocolRegistry/UnregisterConsumer"
	ProtocolRegistry_GetGrpcView_FullMethodName          = "/registry.v1.ProtocolRegistry/GetGrpcView"
	ProtocolRegistry_ListServices_FullMethodName         = "/registry.v1.ProtocolRegistry/ListServices"
	ProtocolRegistry_ListProtocolVersions_FullMethodName = "/registry.v1.ProtocolRegistry/ListProtocolVersions"
)

// ProtocolRegistryClient is the client API for ProtocolRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProtocolRegistryClient interface {
	// Publish a protocol for a service
	PublishProtocol(ctx context.Context, in *PublishProtocolRequest, opts ...grpc.CallOption) (*PublishProtocolResponse, error)
	// Get the current protocol for a service
	GetProtocol(ctx context.Context, in *GetProtocolRequest, opts ...grpc.CallOption) (*GetProtocolResponse, error)
	// Register a consumer of a service's protocol
	RegisterConsumer(ctx context.Context, in *RegisterConsumerRequest, opts ...grpc.CallOption) (*RegisterConsumerResponse, error)
	// Unregister a consumer of a service's protocol
	UnregisterConsumer(ctx context.Context, in *UnregisterConsumerRequest, opts ...grpc.CallOption) (*UnregisterConsumerResponse, error)
	// Get a gRPC view of a service's API with consumer usage
	GetGrpcView(ctx context.Context, in *GetGrpcViewRequest, opts ...grpc.CallOption) (*GetGrpcViewResponse, error)
	// List all registered services
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
	// List version history for a service protocol
	ListProtocolVersions(ctx context.Context, in *ListProtocolVersionsRequest, opts ...grpc.CallOption) (*ListProtocolVersionsResponse, error)
}

type protocolRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewProtocolRegistryClient(cc grpc.ClientConnInterface) ProtocolRegistryClient {
	return &protocolRegistryClient{cc}
}

func (c *protocolRegistryClient) PublishProtocol(ctx context.Context, in *PublishProtocolRequest, opts ...grpc.CallOption) (*PublishProtocolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishProtocolResponse)
	err := c.cc.Invoke(ctx, ProtocolRegistry_PublishProtocol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protocolRegistryClient) GetProtocol(ctx context.Context, in *GetProtocolRequest, opts ...grpc.CallOption) (*GetProtocolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProtocolResponse)
	err := c.cc.Invoke(ctx, ProtocolRegistry_GetProtocol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protocolRegistryClient) RegisterConsumer(ctx context.Context, in *RegisterConsumerRequest, opts ...grpc.CallOption) (*RegisterConsumerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterConsumerResponse)
	err := c.cc.Invoke(ctx, ProtocolRegistry_RegisterConsumer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protocolRegistryClient) UnregisterConsumer(ctx context.Context, in *UnregisterConsumerRequest, opts ...grpc.CallOption) (*UnregisterConsumerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterConsumerResponse)
	err := c.cc.Invoke(ctx, ProtocolRegistry_UnregisterConsumer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protocolRegistryClient) GetGrpcView(ctx context.Context, in *GetGrpcViewRequest, opts ...grpc.CallOption) (*GetGrpcViewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGrpcViewResponse)
	err := c.cc.Invoke(ctx, ProtocolRegistry_GetGrpcView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protocolRegistryClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, ProtocolRegistry_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protocolRegistryClient) ListProtocolVersions(ctx context.Context, in *ListProtocolVersionsRequest, opts ...grpc.CallOption) (*ListProtocolVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProtocolVersionsResponse)
	err := c.cc.Invoke(ctx, ProtocolRegistry_ListProtocolVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProtocolRegistryServer is the server API for ProtocolRegistry service.
// All implementations must embed UnimplementedProtocolRegistryServer
// for forward compatibility.
type ProtocolRegistryServer interface {
	// Publish a protocol for a service
	PublishProtocol(context.Context, *PublishProtocolRequest) (*PublishProtocolResponse, error)
	// Get the current protocol for a service
	GetProtocol(context.Context, *GetProtocolRequest) (*GetProtocolResponse, error)
	// Register a consumer of a service's protocol
	RegisterConsumer(context.Context, *RegisterConsumerRequest) (*RegisterConsumerResponse, error)
	// Unregister a consumer of a service's protocol
	UnregisterConsumer(context.Context, *UnregisterConsumerRequest) (*UnregisterConsumerResponse, error)
	// Get a gRPC view of a service's API with consumer usage
	GetGrpcView(context.Context, *GetGrpcViewRequest) (*GetGrpcViewResponse, error)
	// List all registered services
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	// List version history for a service protocol
	ListProtocolVersions(context.Context, *ListProtocolVersionsRequest) (*ListProtocolVersionsResponse, error)
	mustEmbedUnimplementedProtocolRegistryServer()
}

// UnimplementedProtocolRegistryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProtocolRegistryServer struct{}

func (UnimplementedProtocolRegistryServer) PublishProtocol(context.Context, *PublishProtocolRequest) (*PublishProtocolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishProtocol not implemented")
}
func (UnimplementedProtocolRegistryServer) GetProtocol(context.Context, *GetProtocolRequest) (*GetProtocolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProtocol not implemented")
}
func (UnimplementedProtocolRegistryServer) RegisterConsumer(context.Context, *RegisterConsumerRequest) (*RegisterConsumerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterConsumer not implemented")
}
func (UnimplementedProtocolRegistryServer) UnregisterConsumer(context.Context, *UnregisterConsumerRequest) (*UnregisterConsumerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterConsumer not implemented")
}
func (UnimplementedProtocolRegistryServer) GetGrpcView(context.Context, *GetGrpcViewRequest) (*GetGrpcViewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGrpcView not implemented")
}
func (UnimplementedProtocolRegistryServer) ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedProtocolRegistryServer) ListProtocolVersions(context.Context, *ListProtocolVersionsRequest) (*ListProtocolVersionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProtocolVersions not implemented")
}
func (UnimplementedProtocolRegistryServer) mustEmbedUnimplementedProtocolRegistryServer() {}
func (UnimplementedProtocolRegistryServer) testEmbeddedByValue()                          {}

// UnsafeProtocolRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProtocolRegistryServer will
// result in compilation errors.
type UnsafeProtocolRegistryServer interface {
	mustEmbedUnimplementedProtocolRegistryServer()
}

func RegisterProtocolRegistryServer(s grpc.ServiceRegistrar, srv ProtocolRegistryServer) {
	// If the following call panics, it indicates UnimplementedProtocolRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProtocolRegistry_ServiceDesc, srv)
}

func _ProtocolRegistry_PublishProtocol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishProtocolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtocolRegistryServer).PublishProtocol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtocolRegistry_PublishProtocol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtocolRegistryServer).PublishProtocol(ctx, req.(*PublishProtocolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtocolRegistry_GetProtocol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProtocolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtocolRegistryServer).GetProtocol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtocolRegistry_GetProtocol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtocolRegistryServer).GetProtocol(ctx, req.(*GetProtocolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtocolRegistry_RegisterConsumer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterConsumerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtocolRegistryServer).RegisterConsumer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtocolRegistry_RegisterConsumer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtocolRegistryServer).RegisterConsumer(ctx, req.(*RegisterConsumerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtocolRegistry_UnregisterConsumer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterConsumerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtocolRegistryServer).UnregisterConsumer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtocolRegistry_UnregisterConsumer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtocolRegistryServer).UnregisterConsumer(ctx, req.(*UnregisterConsumerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtocolRegistry_GetGrpcView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGrpcViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtocolRegistryServer).GetGrpcView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtocolRegistry_GetGrpcView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtocolRegistryServer).GetGrpcView(ctx, req.(*GetGrpcViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtocolRegistry_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtocolRegistryServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtocolRegistry_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtocolRegistryServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtocolRegistry_ListProtocolVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProtocolVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtocolRegistryServer).ListProtocolVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtocolRegistry_ListProtocolVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtocolRegistryServer).ListProtocolVersions(ctx, req.(*ListProtocolVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProtocolRegistry_ServiceDesc is the grpc.ServiceDesc for ProtocolRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProtocolRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "registry.v1.ProtocolRegistry",
	HandlerType: (*ProtocolRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishProtocol",
			Handler:    _ProtocolRegistry_PublishProtocol_Handler,
		},
		{
			MethodName: "GetProtocol",
			Handler:    _ProtocolRegistry_GetProtocol_Handler,
		},
		{
			MethodName: "RegisterConsumer",
			Handler:    _ProtocolRegistry_RegisterConsumer_Handler,
		},
		{
			MethodName: "UnregisterConsumer",
			Handler:    _ProtocolRegistry_UnregisterConsumer_Handler,
		},
		{
			MethodName: "GetGrpcView",
			Handler:    _ProtocolRegistry_GetGrpcView_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _ProtocolRegistry_ListServices_Handler,
		},
		{
			MethodName: "ListProtocolVersions",
			Handler:    _ProtocolRegistry_ListProtocolVersions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "registry/v1/registry.proto",
}
