// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: registry/v1/registry.proto

package registryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtocolType int32

const (
	ProtocolType_PROTOCOL_TYPE_UNSPECIFIED ProtocolType = 0
	ProtocolType_PROTOCOL_TYPE_GRPC        ProtocolType = 1
)

// Enum value maps for ProtocolType.
var (
	ProtocolType_name = map[int32]string{
		0: "PROTOCOL_TYPE_UNSPECIFIED",
		1: "PROTOCOL_TYPE_GRPC",
	}
	ProtocolType_value = map[string]int32{
		"PROTOCOL_TYPE_UNSPECIFIED": 0,
		"PROTOCOL_TYPE_GRPC":        1,
	}
)

func (x ProtocolType) Enum() *ProtocolType {
	p := new(ProtocolType)
	*p = x
	return p
}

func (x ProtocolType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtocolType) Descriptor() protoreflect.EnumDescriptor {
	return file_registry_v1_registry_proto_enumTypes[0].Descriptor()
}

func (ProtocolType) Type() protoreflect.EnumType {
	return &file_registry_v1_registry_proto_enumTypes[0]
}

func (x ProtocolType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtocolType.Descriptor instead.
func (ProtocolType) EnumDescriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{0}
}

type ProtoFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoFile) Reset() {
	*x = ProtoFile{}
	mi := &file_registry_v1_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoFile) ProtoMessage() {}

func (x *ProtoFile) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoFile.ProtoReflect.Descriptor instead.
func (*ProtoFile) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ProtoFile) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type PublishProtocolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ProtocolType  ProtocolType           `protobuf:"varint,3,opt,name=protocol_type,json=protocolType,proto3,enum=registry.v1.ProtocolType" json:"protocol_type,omitempty"`
	Files         []*ProtoFile           `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	EntryPoint    string                 `protobuf:"bytes,5,opt,name=entry_point,json=entryPoint,proto3" json:"entry_point,omitempty"`
	Versions      []string               `protobuf:"bytes,6,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishProtocolRequest) Reset() {
	*x = PublishProtocolRequest{}
	mi := &file_registry_v1_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishProtocolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishProtocolRequest) ProtoMessage() {}

func (x *PublishProtocolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishProtocolRequest.ProtoReflect.Descriptor instead.
func (*PublishProtocolRequest) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{1}
}

func (x *PublishProtocolRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *PublishProtocolRequest) GetProtocolType() ProtocolType {
	if x != nil {
		return x.ProtocolType
	}
	return ProtocolType_PROTOCOL_TYPE_UNSPECIFIED
}

func (x *PublishProtocolRequest) GetFiles() []*ProtoFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *PublishProtocolRequest) GetEntryPoint() string {
	if x != nil {
		return x.EntryPoint
	}
	return ""
}

func (x *PublishProtocolRequest) GetVersions() []string {
	if x != nil {
		return x.Versions
	}
	return nil
}

type PublishProtocolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	IsNew         bool                   `protobuf:"varint,2,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishProtocolResponse) Reset() {
	*x = PublishProtocolResponse{}
	mi := &file_registry_v1_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishProtocolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishProtocolResponse) ProtoMessage() {}

func (x *PublishProtocolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishProtocolResponse.ProtoReflect.Descriptor instead.
func (*PublishProtocolResponse) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{2}
}

func (x *PublishProtocolResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *PublishProtocolResponse) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

type GetProtocolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ProtocolType  ProtocolType           `protobuf:"varint,2,opt,name=protocol_type,json=protocolType,proto3,enum=registry.v1.ProtocolType" json:"protocol_type,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProtocolRequest) Reset() {
	*x = GetProtocolRequest{}
	mi := &file_registry_v1_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProtocolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProtocolRequest) ProtoMessage() {}

func (x *GetProtocolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProtocolRequest.ProtoReflect.Descriptor instead.
func (*GetProtocolRequest) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{3}
}

func (x *GetProtocolRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetProtocolRequest) GetProtocolType() ProtocolType {
	if x != nil {
		return x.ProtocolType
	}
	return ProtocolType_PROTOCOL_TYPE_UNSPECIFIED
}

func (x *GetProtocolRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetProtocolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ProtocolType  ProtocolType           `protobuf:"varint,2,opt,name=protocol_type,json=protocolType,proto3,enum=registry.v1.ProtocolType" json:"protocol_type,omitempty"`
	Files         []*ProtoFile           `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	EntryPoint    string                 `protobuf:"bytes,5,opt,name=entry_point,json=entryPoint,proto3" json:"entry_point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProtocolResponse) Reset() {
	*x = GetProtocolResponse{}
	mi := &file_registry_v1_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProtocolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProtocolResponse) ProtoMessage() {}

func (x *GetProtocolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProtocolResponse.ProtoReflect.Descriptor instead.
func (*GetProtocolResponse) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{4}
}

func (x *GetProtocolResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetProtocolResponse) GetProtocolType() ProtocolType {
	if x != nil {
		return x.ProtocolType
	}
	return ProtocolType_PROTOCOL_TYPE_UNSPECIFIED
}

func (x *GetProtocolResponse) GetFiles() []*ProtoFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *GetProtocolResponse) GetEntryPoint() string {
	if x != nil {
		return x.EntryPoint
	}
	return ""
}

type RegisterConsumerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConsumerName   string                 `protobuf:"bytes,1,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	ServerName     string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	ProtocolType   ProtocolType           `protobuf:"varint,3,opt,name=protocol_type,json=protocolType,proto3,enum=registry.v1.ProtocolType" json:"protocol_type,omitempty"`
	Files          []*ProtoFile           `protobuf:"bytes,5,rep,name=files,proto3" json:"files,omitempty"`
	EntryPoint     string                 `protobuf:"bytes,6,opt,name=entry_point,json=entryPoint,proto3" json:"entry_point,omitempty"`
	ServerVersions []string               `protobuf:"bytes,7,rep,name=server_versions,json=serverVersions,proto3" json:"server_versions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterConsumerRequest) Reset() {
	*x = RegisterConsumerRequest{}
	mi := &file_registry_v1_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterConsumerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConsumerRequest) ProtoMessage() {}

func (x *RegisterConsumerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConsumerRequest.ProtoReflect.Descriptor instead.
func (*RegisterConsumerRequest) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterConsumerRequest) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

func (x *RegisterConsumerRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *RegisterConsumerRequest) GetProtocolType() ProtocolType {
	if x != nil {
		return x.ProtocolType
	}
	return ProtocolType_PROTOCOL_TYPE_UNSPECIFIED
}

func (x *RegisterConsumerRequest) GetFiles() []*ProtoFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *RegisterConsumerRequest) GetEntryPoint() string {
	if x != nil {
		return x.EntryPoint
	}
	return ""
}

func (x *RegisterConsumerRequest) GetServerVersions() []string {
	if x != nil {
		return x.ServerVersions
	}
	return nil
}

type RegisterConsumerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerName  string                 `protobuf:"bytes,1,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	ServerName    string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	IsNew         bool                   `protobuf:"varint,3,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterConsumerResponse) Reset() {
	*x = RegisterConsumerResponse{}
	mi := &file_registry_v1_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterConsumerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConsumerResponse) ProtoMessage() {}

func (x *RegisterConsumerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConsumerResponse.ProtoReflect.Descriptor instead.
func (*RegisterConsumerResponse) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterConsumerResponse) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

func (x *RegisterConsumerResponse) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *RegisterConsumerResponse) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

type UnregisterConsumerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConsumerName   string                 `protobuf:"bytes,1,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	ServerName     string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	ProtocolType   ProtocolType           `protobuf:"varint,3,opt,name=protocol_type,json=protocolType,proto3,enum=registry.v1.ProtocolType" json:"protocol_type,omitempty"`
	ServerVersions []string               `protobuf:"bytes,4,rep,name=server_versions,json=serverVersions,proto3" json:"server_versions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UnregisterConsumerRequest) Reset() {
	*x = UnregisterConsumerRequest{}
	mi := &file_registry_v1_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterConsumerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterConsumerRequest) ProtoMessage() {}

func (x *UnregisterConsumerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterConsumerRequest.ProtoReflect.Descriptor instead.
func (*UnregisterConsumerRequest) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{7}
}

func (x *UnregisterConsumerRequest) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

func (x *UnregisterConsumerRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *UnregisterConsumerRequest) GetProtocolType() ProtocolType {
	if x != nil {
		return x.ProtocolType
	}
	return ProtocolType_PROTOCOL_TYPE_UNSPECIFIED
}

func (x *UnregisterConsumerRequest) GetServerVersions() []string {
	if x != nil {
		return x.ServerVersions
	}
	return nil
}

type UnregisterConsumerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterConsumerResponse) Reset() {
	*x = UnregisterConsumerResponse{}
	mi := &file_registry_v1_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterConsumerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterConsumerResponse) ProtoMessage() {}

func (x *UnregisterConsumerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterConsumerResponse.ProtoReflect.Descriptor instead.
func (*UnregisterConsumerResponse) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{8}
}

type GetGrpcViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGrpcViewRequest) Reset() {
	*x = GetGrpcViewRequest{}
	mi := &file_registry_v1_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGrpcViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGrpcViewRequest) ProtoMessage() {}

func (x *GetGrpcViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGrpcViewRequest.ProtoReflect.Descriptor instead.
func (*GetGrpcViewRequest) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{9}
}

func (x *GetGrpcViewRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type GetGrpcViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Services      []*GrpcServiceView     `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGrpcViewResponse) Reset() {
	*x = GetGrpcViewResponse{}
	mi := &file_registry_v1_registry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGrpcViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGrpcViewResponse) ProtoMessage() {}

func (x *GetGrpcViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGrpcViewResponse.ProtoReflect.Descriptor instead.
func (*GetGrpcViewResponse) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{10}
}

func (x *GetGrpcViewResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetGrpcViewResponse) GetServices() []*GrpcServiceView {
	if x != nil {
		return x.Services
	}
	return nil
}

type GrpcServiceView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Methods       []*GrpcMethodView      `protobuf:"bytes,2,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcServiceView) Reset() {
	*x = GrpcServiceView{}
	mi := &file_registry_v1_registry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcServiceView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcServiceView) ProtoMessage() {}

func (x *GrpcServiceView) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcServiceView.ProtoReflect.Descriptor instead.
func (*GrpcServiceView) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{11}
}

func (x *GrpcServiceView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GrpcServiceView) GetMethods() []*GrpcMethodView {
	if x != nil {
		return x.Methods
	}
	return nil
}

type GrpcMethodView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Input         *GrpcMessageView       `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Output        *GrpcMessageView       `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Consumers     []string               `protobuf:"bytes,4,rep,name=consumers,proto3" json:"consumers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcMethodView) Reset() {
	*x = GrpcMethodView{}
	mi := &file_registry_v1_registry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcMethodView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcMethodView) ProtoMessage() {}

func (x *GrpcMethodView) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcMethodView.ProtoReflect.Descriptor instead.
func (*GrpcMethodView) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{12}
}

func (x *GrpcMethodView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GrpcMethodView) GetInput() *GrpcMessageView {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *GrpcMethodView) GetOutput() *GrpcMessageView {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *GrpcMethodView) GetConsumers() []string {
	if x != nil {
		return x.Consumers
	}
	return nil
}

type GrpcMessageView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fields        []*GrpcFieldView       `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcMessageView) Reset() {
	*x = GrpcMessageView{}
	mi := &file_registry_v1_registry_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcMessageView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcMessageView) ProtoMessage() {}

func (x *GrpcMessageView) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcMessageView.ProtoReflect.Descriptor instead.
func (*GrpcMessageView) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{13}
}

func (x *GrpcMessageView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GrpcMessageView) GetFields() []*GrpcFieldView {
	if x != nil {
		return x.Fields
	}
	return nil
}

type GrpcFieldView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Number        uint32                 `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	Consumers     []string               `protobuf:"bytes,4,rep,name=consumers,proto3" json:"consumers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcFieldView) Reset() {
	*x = GrpcFieldView{}
	mi := &file_registry_v1_registry_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcFieldView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcFieldView) ProtoMessage() {}

func (x *GrpcFieldView) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcFieldView.ProtoReflect.Descriptor instead.
func (*GrpcFieldView) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{14}
}

func (x *GrpcFieldView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GrpcFieldView) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GrpcFieldView) GetNumber() uint32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *GrpcFieldView) GetConsumers() []string {
	if x != nil {
		return x.Consumers
	}
	return nil
}

type ListServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_registry_v1_registry_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{15}
}

type ListServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceInfo         `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_registry_v1_registry_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{16}
}

func (x *ListServicesResponse) GetServices() []*ServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_registry_v1_registry_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{17}
}

func (x *ServiceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ValidateProtocolRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServiceName     string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ProtocolType    ProtocolType           `protobuf:"varint,2,opt,name=protocol_type,json=protocolType,proto3,enum=registry.v1.ProtocolType" json:"protocol_type,omitempty"`
	Files           []*ProtoFile           `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	EntryPoint      string                 `protobuf:"bytes,4,opt,name=entry_point,json=entryPoint,proto3" json:"entry_point,omitempty"`
	AgainstVersions []string               `protobuf:"bytes,5,rep,name=against_versions,json=againstVersions,proto3" json:"against_versions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ValidateProtocolRequest) Reset() {
	*x = ValidateProtocolRequest{}
	mi := &file_registry_v1_registry_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateProtocolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateProtocolRequest) ProtoMessage() {}

func (x *ValidateProtocolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateProtocolRequest.ProtoReflect.Descriptor instead.
func (*ValidateProtocolRequest) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{18}
}

func (x *ValidateProtocolRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ValidateProtocolRequest) GetProtocolType() ProtocolType {
	if x != nil {
		return x.ProtocolType
	}
	return ProtocolType_PROTOCOL_TYPE_UNSPECIFIED
}

func (x *ValidateProtocolRequest) GetFiles() []*ProtoFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ValidateProtocolRequest) GetEntryPoint() string {
	if x != nil {
		return x.EntryPoint
	}
	return ""
}

func (x *ValidateProtocolRequest) GetAgainstVersions() []string {
	if x != nil {
		return x.AgainstVersions
	}
	return nil
}

type VersionViolation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Consumers     []*ConsumerViolation   `protobuf:"bytes,2,rep,name=consumers,proto3" json:"consumers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionViolation) Reset() {
	*x = VersionViolation{}
	mi := &file_registry_v1_registry_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionViolation) ProtoMessage() {}

func (x *VersionViolation) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionViolation.ProtoReflect.Descriptor instead.
func (*VersionViolation) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{19}
}

func (x *VersionViolation) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VersionViolation) GetConsumers() []*ConsumerViolation {
	if x != nil {
		return x.Consumers
	}
	return nil
}

type ConsumerViolation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerName  string                 `protobuf:"bytes,1,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	Violations    []string               `protobuf:"bytes,2,rep,name=violations,proto3" json:"violations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumerViolation) Reset() {
	*x = ConsumerViolation{}
	mi := &file_registry_v1_registry_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerViolation) ProtoMessage() {}

func (x *ConsumerViolation) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerViolation.ProtoReflect.Descriptor instead.
func (*ConsumerViolation) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{20}
}

func (x *ConsumerViolation) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

func (x *ConsumerViolation) GetViolations() []string {
	if x != nil {
		return x.Violations
	}
	return nil
}

type ValidateProtocolResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Valid             bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	VersionViolations []*VersionViolation    `protobuf:"bytes,2,rep,name=version_violations,json=versionViolations,proto3" json:"version_violations,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ValidateProtocolResponse) Reset() {
	*x = ValidateProtocolResponse{}
	mi := &file_registry_v1_registry_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateProtocolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateProtocolResponse) ProtoMessage() {}

func (x *ValidateProtocolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateProtocolResponse.ProtoReflect.Descriptor instead.
func (*ValidateProtocolResponse) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{21}
}

func (x *ValidateProtocolResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateProtocolResponse) GetVersionViolations() []*VersionViolation {
	if x != nil {
		return x.VersionViolations
	}
	return nil
}

var File_registry_v1_registry_proto protoreflect.FileDescriptor

const file_registry_v1_registry_proto_rawDesc = "" +
	"\n" +
	"\x1aregistry/v1/registry.proto\x12\vregistry.v1\"9\n" +
	"\tProtoFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"\xec\x01\n" +
	"\x16PublishProtocolRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12>\n" +
	"\rprotocol_type\x18\x03 \x01(\x0e2\x19.registry.v1.ProtocolTypeR\fprotocolType\x12,\n" +
	"\x05files\x18\x04 \x03(\v2\x16.registry.v1.ProtoFileR\x05files\x12\x1f\n" +
	"\ventry_point\x18\x05 \x01(\tR\n" +
	"entryPoint\x12\x1a\n" +
	"\bversions\x18\x06 \x03(\tR\bversionsJ\x04\b\x02\x10\x03\"S\n" +
	"\x17PublishProtocolResponse\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x15\n" +
	"\x06is_new\x18\x02 \x01(\bR\x05isNew\"\x91\x01\n" +
	"\x12GetProtocolRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12>\n" +
	"\rprotocol_type\x18\x02 \x01(\x0e2\x19.registry.v1.ProtocolTypeR\fprotocolType\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\xcd\x01\n" +
	"\x13GetProtocolResponse\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12>\n" +
	"\rprotocol_type\x18\x02 \x01(\x0e2\x19.registry.v1.ProtocolTypeR\fprotocolType\x12,\n" +
	"\x05files\x18\x04 \x03(\v2\x16.registry.v1.ProtoFileR\x05files\x12\x1f\n" +
	"\ventry_point\x18\x05 \x01(\tR\n" +
	"entryPointJ\x04\b\x03\x10\x04\"\x9d\x02\n" +
	"\x17RegisterConsumerRequest\x12#\n" +
	"\rconsumer_name\x18\x01 \x01(\tR\fconsumerName\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x12>\n" +
	"\rprotocol_type\x18\x03 \x01(\x0e2\x19.registry.v1.ProtocolTypeR\fprotocolType\x12,\n" +
	"\x05files\x18\x05 \x03(\v2\x16.registry.v1.ProtoFileR\x05files\x12\x1f\n" +
	"\ventry_point\x18\x06 \x01(\tR\n" +
	"entryPoint\x12'\n" +
	"\x0fserver_versions\x18\a \x03(\tR\x0eserverVersionsJ\x04\b\x04\x10\x05\"w\n" +
	"\x18RegisterConsumerResponse\x12#\n" +
	"\rconsumer_name\x18\x01 \x01(\tR\fconsumerName\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x12\x15\n" +
	"\x06is_new\x18\x03 \x01(\bR\x05isNew\"\xca\x01\n" +
	"\x19UnregisterConsumerRequest\x12#\n" +
	"\rconsumer_name\x18\x01 \x01(\tR\fconsumerName\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x12>\n" +
	"\rprotocol_type\x18\x03 \x01(\x0e2\x19.registry.v1.ProtocolTypeR\fprotocolType\x12'\n" +
	"\x0fserver_versions\x18\x04 \x03(\tR\x0eserverVersions\"\x1c\n" +
	"\x1aUnregisterConsumerResponse\"7\n" +
	"\x12GetGrpcViewRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"r\n" +
	"\x13GetGrpcViewResponse\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x128\n" +
	"\bservices\x18\x02 \x03(\v2\x1c.registry.v1.GrpcServiceViewR\bservices\"\\\n" +
	"\x0fGrpcServiceView\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\amethods\x18\x02 \x03(\v2\x1b.registry.v1.GrpcMethodViewR\amethods\"\xac\x01\n" +
	"\x0eGrpcMethodView\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x05input\x18\x02 \x01(\v2\x1c.registry.v1.GrpcMessageViewR\x05input\x124\n" +
	"\x06output\x18\x03 \x01(\v2\x1c.registry.v1.GrpcMessageViewR\x06output\x12\x1c\n" +
	"\tconsumers\x18\x04 \x03(\tR\tconsumers\"Y\n" +
	"\x0fGrpcMessageView\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x06fields\x18\x02 \x03(\v2\x1a.registry.v1.GrpcFieldViewR\x06fields\"m\n" +
	"\rGrpcFieldView\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06number\x18\x03 \x01(\rR\x06number\x12\x1c\n" +
	"\tconsumers\x18\x04 \x03(\tR\tconsumers\"\x15\n" +
	"\x13ListServicesRequest\"L\n" +
	"\x14ListServicesResponse\x124\n" +
	"\bservices\x18\x01 \x03(\v2\x18.registry.v1.ServiceInfoR\bservices\"1\n" +
	"\vServiceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xf6\x01\n" +
	"\x17ValidateProtocolRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12>\n" +
	"\rprotocol_type\x18\x02 \x01(\x0e2\x19.registry.v1.ProtocolTypeR\fprotocolType\x12,\n" +
	"\x05files\x18\x03 \x03(\v2\x16.registry.v1.ProtoFileR\x05files\x12\x1f\n" +
	"\ventry_point\x18\x04 \x01(\tR\n" +
	"entryPoint\x12)\n" +
	"\x10against_versions\x18\x05 \x03(\tR\x0fagainstVersions\"j\n" +
	"\x10VersionViolation\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12<\n" +
	"\tconsumers\x18\x02 \x03(\v2\x1e.registry.v1.ConsumerViolationR\tconsumers\"X\n" +
	"\x11ConsumerViolation\x12#\n" +
	"\rconsumer_name\x18\x01 \x01(\tR\fconsumerName\x12\x1e\n" +
	"\n" +
	"violations\x18\x02 \x03(\tR\n" +
	"violations\"~\n" +
	"\x18ValidateProtocolResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12L\n" +
	"\x12version_violations\x18\x02 \x03(\v2\x1d.registry.v1.VersionViolationR\x11versionViolations*E\n" +
	"\fProtocolType\x12\x1d\n" +
	"\x19PROTOCOL_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PROTOCOL_TYPE_GRPC\x10\x012\x92\x05\n" +
	"\x10ProtocolRegistry\x12\\\n" +
	"\x0fPublishProtocol\x12#.registry.v1.PublishProtocolRequest\x1a$.registry.v1.PublishProtocolResponse\x12P\n" +
	"\vGetProtocol\x12\x1f.registry.v1.GetProtocolRequest\x1a .registry.v1.GetProtocolResponse\x12_\n" +
	"\x10RegisterConsumer\x12$.registry.v1.RegisterConsumerRequest\x1a%.registry.v1.RegisterConsumerResponse\x12e\n" +
	"\x12UnregisterConsumer\x12&.registry.v1.UnregisterConsumerRequest\x1a'.registry.v1.UnregisterConsumerResponse\x12P\n" +
	"\vGetGrpcView\x12\x1f.registry.v1.GetGrpcViewRequest\x1a .registry.v1.GetGrpcViewResponse\x12S\n" +
	"\fListServices\x12 .registry.v1.ListServicesRequest\x1a!.registry.v1.ListServicesResponse\x12_\n" +
	"\x10ValidateProtocol\x12$.registry.v1.ValidateProtocolRequest\x1a%.registry.v1.ValidateProtocolResponseB\xaf\x01\n" +
	"\x0fcom.registry.v1B\rRegistryProtoP\x01Z@github.com/user/protocol_registry/pkg/api/registry/v1;registryv1\xa2\x02\x03RXX\xaa\x02\vRegistry.V1\xca\x02\vRegistry\\V1\xe2\x02\x17Registry\\V1\\GPBMetadata\xea\x02\fRegistry::V1b\x06proto3"

var (
	file_registry_v1_registry_proto_rawDescOnce sync.Once
	file_registry_v1_registry_proto_rawDescData []byte
)

func file_registry_v1_registry_proto_rawDescGZIP() []byte {
	file_registry_v1_registry_proto_rawDescOnce.Do(func() {
		file_registry_v1_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_registry_v1_registry_proto_rawDesc), len(file_registry_v1_registry_proto_rawDesc)))
	})
	return file_registry_v1_registry_proto_rawDescData
}

var file_registry_v1_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_registry_v1_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_registry_v1_registry_proto_goTypes = []any{
	(ProtocolType)(0),                  // 0: registry.v1.ProtocolType
	(*ProtoFile)(nil),                  // 1: registry.v1.ProtoFile
	(*PublishProtocolRequest)(nil),     // 2: registry.v1.PublishProtocolRequest
	(*PublishProtocolResponse)(nil),    // 3: registry.v1.PublishProtocolResponse
	(*GetProtocolRequest)(nil),         // 4: registry.v1.GetProtocolRequest
	(*GetProtocolResponse)(nil),        // 5: registry.v1.GetProtocolResponse
	(*RegisterConsumerRequest)(nil),    // 6: registry.v1.RegisterConsumerRequest
	(*RegisterConsumerResponse)(nil),   // 7: registry.v1.RegisterConsumerResponse
	(*UnregisterConsumerRequest)(nil),  // 8: registry.v1.UnregisterConsumerRequest
	(*UnregisterConsumerResponse)(nil), // 9: registry.v1.UnregisterConsumerResponse
	(*GetGrpcViewRequest)(nil),         // 10: registry.v1.GetGrpcViewRequest
	(*GetGrpcViewResponse)(nil),        // 11: registry.v1.GetGrpcViewResponse
	(*GrpcServiceView)(nil),            // 12: registry.v1.GrpcServiceView
	(*GrpcMethodView)(nil),             // 13: registry.v1.GrpcMethodView
	(*GrpcMessageView)(nil),            // 14: registry.v1.GrpcMessageView
	(*GrpcFieldView)(nil),              // 15: registry.v1.GrpcFieldView
	(*ListServicesRequest)(nil),        // 16: registry.v1.ListServicesRequest
	(*ListServicesResponse)(nil),       // 17: registry.v1.ListServicesResponse
	(*ServiceInfo)(nil),                // 18: registry.v1.ServiceInfo
	(*ValidateProtocolRequest)(nil),    // 19: registry.v1.ValidateProtocolRequest
	(*VersionViolation)(nil),           // 20: registry.v1.VersionViolation
	(*ConsumerViolation)(nil),          // 21: registry.v1.ConsumerViolation
	(*ValidateProtocolResponse)(nil),   // 22: registry.v1.ValidateProtocolResponse
}
var file_registry_v1_registry_proto_depIdxs = []int32{
	0,  // 0: registry.v1.PublishProtocolRequest.protocol_type:type_name -> registry.v1.ProtocolType
	1,  // 1: registry.v1.PublishProtocolRequest.files:type_name -> registry.v1.ProtoFile
	0,  // 2: registry.v1.GetProtocolRequest.protocol_type:type_name -> registry.v1.ProtocolType
	0,  // 3: registry.v1.GetProtocolResponse.protocol_type:type_name -> registry.v1.ProtocolType
	1,  // 4: registry.v1.GetProtocolResponse.files:type_name -> registry.v1.ProtoFile
	0,  // 5: registry.v1.RegisterConsumerRequest.protocol_type:type_name -> registry.v1.ProtocolType
	1,  // 6: registry.v1.RegisterConsumerRequest.files:type_name -> registry.v1.ProtoFile
	0,  // 7: registry.v1.UnregisterConsumerRequest.protocol_type:type_name -> registry.v1.ProtocolType
	12, // 8: registry.v1.GetGrpcViewResponse.services:type_name -> registry.v1.GrpcServiceView
	13, // 9: registry.v1.GrpcServiceView.methods:type_name -> registry.v1.GrpcMethodView
	14, // 10: registry.v1.GrpcMethodView.input:type_name -> registry.v1.GrpcMessageView
	14, // 11: registry.v1.GrpcMethodView.output:type_name -> registry.v1.GrpcMessageView
	15, // 12: registry.v1.GrpcMessageView.fields:type_name -> registry.v1.GrpcFieldView
	18, // 13: registry.v1.ListServicesResponse.services:type_name -> registry.v1.ServiceInfo
	0,  // 14: registry.v1.ValidateProtocolRequest.protocol_type:type_name -> registry.v1.ProtocolType
	1,  // 15: registry.v1.ValidateProtocolRequest.files:type_name -> registry.v1.ProtoFile
	21, // 16: registry.v1.VersionViolation.consumers:type_name -> registry.v1.ConsumerViolation
	20, // 17: registry.v1.ValidateProtocolResponse.version_violations:type_name -> registry.v1.VersionViolation
	2,  // 18: registry.v1.ProtocolRegistry.PublishProtocol:input_type -> registry.v1.PublishProtocolRequest
	4,  // 19: registry.v1.ProtocolRegistry.GetProtocol:input_type -> registry.v1.GetProtocolRequest
	6,  // 20: registry.v1.ProtocolRegistry.RegisterConsumer:input_type -> registry.v1.RegisterConsumerRequest
	8,  // 21: registry.v1.ProtocolRegistry.UnregisterConsumer:input_type -> registry.v1.UnregisterConsumerRequest
	10, // 22: registry.v1.ProtocolRegistry.GetGrpcView:input_type -> registry.v1.GetGrpcViewRequest
	16, // 23: registry.v1.ProtocolRegistry.ListServices:input_type -> registry.v1.ListServicesRequest
	19, // 24: registry.v1.ProtocolRegistry.ValidateProtocol:input_type -> registry.v1.ValidateProtocolRequest
	3,  // 25: registry.v1.ProtocolRegistry.PublishProtocol:output_type -> registry.v1.PublishProtocolResponse
	5,  // 26: registry.v1.ProtocolRegistry.GetProtocol:output_type -> registry.v1.GetProtocolResponse
	7,  // 27: registry.v1.ProtocolRegistry.RegisterConsumer:output_type -> registry.v1.RegisterConsumerResponse
	9,  // 28: registry.v1.ProtocolRegistry.UnregisterConsumer:output_type -> registry.v1.UnregisterConsumerResponse
	11, // 29: registry.v1.ProtocolRegistry.GetGrpcView:output_type -> registry.v1.GetGrpcViewResponse
	17, // 30: registry.v1.ProtocolRegistry.ListServices:output_type -> registry.v1.ListServicesResponse
	22, // 31: registry.v1.ProtocolRegistry.ValidateProtocol:output_type -> registry.v1.ValidateProtocolResponse
	25, // [25:32] is the sub-list for method output_type
	18, // [18:25] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_registry_v1_registry_proto_init() }
func file_registry_v1_registry_proto_init() {
	if File_registry_v1_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_registry_v1_registry_proto_rawDesc), len(file_registry_v1_registry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_registry_v1_registry_proto_goTypes,
		DependencyIndexes: file_registry_v1_registry_proto_depIdxs,
		EnumInfos:         file_registry_v1_registry_proto_enumTypes,
		MessageInfos:      file_registry_v1_registry_proto_msgTypes,
	}.Build()
	File_registry_v1_registry_proto = out.File
	file_registry_v1_registry_proto_goTypes = nil
	file_registry_v1_registry_proto_depIdxs = nil
}
