// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: registry/v1/registry.proto

package registryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtocolType int32

const (
	ProtocolType_PROTOCOL_TYPE_UNSPECIFIED ProtocolType = 0
	ProtocolType_PROTOCOL_TYPE_GRPC        ProtocolType = 1
	ProtocolType_PROTOCOL_TYPE_OPENAPI     ProtocolType = 2 // Future: PROTOCOL_TYPE_ASYNCAPI = 3;
)

// Enum value maps for ProtocolType.
var (
	ProtocolType_name = map[int32]string{
		0: "PROTOCOL_TYPE_UNSPECIFIED",
		1: "PROTOCOL_TYPE_GRPC",
		2: "PROTOCOL_TYPE_OPENAPI",
	}
	ProtocolType_value = map[string]int32{
		"PROTOCOL_TYPE_UNSPECIFIED": 0,
		"PROTOCOL_TYPE_GRPC":        1,
		"PROTOCOL_TYPE_OPENAPI":     2,
	}
)

func (x ProtocolType) Enum() *ProtocolType {
	p := new(ProtocolType)
	*p = x
	return p
}

func (x ProtocolType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtocolType) Descriptor() protoreflect.EnumDescriptor {
	return file_registry_v1_registry_proto_enumTypes[0].Descriptor()
}

func (ProtocolType) Type() protoreflect.EnumType {
	return &file_registry_v1_registry_proto_enumTypes[0]
}

func (x ProtocolType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtocolType.Descriptor instead.
func (ProtocolType) EnumDescriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{0}
}

type ProtoFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoFile) Reset() {
	*x = ProtoFile{}
	mi := &file_registry_v1_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoFile) ProtoMessage() {}

func (x *ProtoFile) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoFile.ProtoReflect.Descriptor instead.
func (*ProtoFile) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ProtoFile) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type PublishProtocolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ProtocolType  ProtocolType           `protobuf:"varint,3,opt,name=protocol_type,json=protocolType,proto3,enum=registry.v1.ProtocolType" json:"protocol_type,omitempty"`
	Files         []*ProtoFile           `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	EntryPoint    string                 `protobuf:"bytes,5,opt,name=entry_point,json=entryPoint,proto3" json:"entry_point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishProtocolRequest) Reset() {
	*x = PublishProtocolRequest{}
	mi := &file_registry_v1_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishProtocolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishProtocolRequest) ProtoMessage() {}

func (x *PublishProtocolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishProtocolRequest.ProtoReflect.Descriptor instead.
func (*PublishProtocolRequest) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{1}
}

func (x *PublishProtocolRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *PublishProtocolRequest) GetProtocolType() ProtocolType {
	if x != nil {
		return x.ProtocolType
	}
	return ProtocolType_PROTOCOL_TYPE_UNSPECIFIED
}

func (x *PublishProtocolRequest) GetFiles() []*ProtoFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *PublishProtocolRequest) GetEntryPoint() string {
	if x != nil {
		return x.EntryPoint
	}
	return ""
}

type PublishProtocolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	IsNew         bool                   `protobuf:"varint,2,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishProtocolResponse) Reset() {
	*x = PublishProtocolResponse{}
	mi := &file_registry_v1_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishProtocolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishProtocolResponse) ProtoMessage() {}

func (x *PublishProtocolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishProtocolResponse.ProtoReflect.Descriptor instead.
func (*PublishProtocolResponse) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{2}
}

func (x *PublishProtocolResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *PublishProtocolResponse) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

type GetProtocolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ProtocolType  ProtocolType           `protobuf:"varint,2,opt,name=protocol_type,json=protocolType,proto3,enum=registry.v1.ProtocolType" json:"protocol_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProtocolRequest) Reset() {
	*x = GetProtocolRequest{}
	mi := &file_registry_v1_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProtocolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProtocolRequest) ProtoMessage() {}

func (x *GetProtocolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProtocolRequest.ProtoReflect.Descriptor instead.
func (*GetProtocolRequest) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{3}
}

func (x *GetProtocolRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetProtocolRequest) GetProtocolType() ProtocolType {
	if x != nil {
		return x.ProtocolType
	}
	return ProtocolType_PROTOCOL_TYPE_UNSPECIFIED
}

type GetProtocolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ProtocolType  ProtocolType           `protobuf:"varint,2,opt,name=protocol_type,json=protocolType,proto3,enum=registry.v1.ProtocolType" json:"protocol_type,omitempty"`
	Files         []*ProtoFile           `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	EntryPoint    string                 `protobuf:"bytes,5,opt,name=entry_point,json=entryPoint,proto3" json:"entry_point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProtocolResponse) Reset() {
	*x = GetProtocolResponse{}
	mi := &file_registry_v1_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProtocolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProtocolResponse) ProtoMessage() {}

func (x *GetProtocolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProtocolResponse.ProtoReflect.Descriptor instead.
func (*GetProtocolResponse) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{4}
}

func (x *GetProtocolResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetProtocolResponse) GetProtocolType() ProtocolType {
	if x != nil {
		return x.ProtocolType
	}
	return ProtocolType_PROTOCOL_TYPE_UNSPECIFIED
}

func (x *GetProtocolResponse) GetFiles() []*ProtoFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *GetProtocolResponse) GetEntryPoint() string {
	if x != nil {
		return x.EntryPoint
	}
	return ""
}

type RegisterConsumerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerName  string                 `protobuf:"bytes,1,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	ServerName    string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	ProtocolType  ProtocolType           `protobuf:"varint,3,opt,name=protocol_type,json=protocolType,proto3,enum=registry.v1.ProtocolType" json:"protocol_type,omitempty"`
	Files         []*ProtoFile           `protobuf:"bytes,5,rep,name=files,proto3" json:"files,omitempty"`
	EntryPoint    string                 `protobuf:"bytes,6,opt,name=entry_point,json=entryPoint,proto3" json:"entry_point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterConsumerRequest) Reset() {
	*x = RegisterConsumerRequest{}
	mi := &file_registry_v1_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterConsumerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConsumerRequest) ProtoMessage() {}

func (x *RegisterConsumerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConsumerRequest.ProtoReflect.Descriptor instead.
func (*RegisterConsumerRequest) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterConsumerRequest) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

func (x *RegisterConsumerRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *RegisterConsumerRequest) GetProtocolType() ProtocolType {
	if x != nil {
		return x.ProtocolType
	}
	return ProtocolType_PROTOCOL_TYPE_UNSPECIFIED
}

func (x *RegisterConsumerRequest) GetFiles() []*ProtoFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *RegisterConsumerRequest) GetEntryPoint() string {
	if x != nil {
		return x.EntryPoint
	}
	return ""
}

type RegisterConsumerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerName  string                 `protobuf:"bytes,1,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	ServerName    string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	IsNew         bool                   `protobuf:"varint,3,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterConsumerResponse) Reset() {
	*x = RegisterConsumerResponse{}
	mi := &file_registry_v1_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterConsumerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConsumerResponse) ProtoMessage() {}

func (x *RegisterConsumerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConsumerResponse.ProtoReflect.Descriptor instead.
func (*RegisterConsumerResponse) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterConsumerResponse) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

func (x *RegisterConsumerResponse) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *RegisterConsumerResponse) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

type UnregisterConsumerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerName  string                 `protobuf:"bytes,1,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	ServerName    string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	ProtocolType  ProtocolType           `protobuf:"varint,3,opt,name=protocol_type,json=protocolType,proto3,enum=registry.v1.ProtocolType" json:"protocol_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterConsumerRequest) Reset() {
	*x = UnregisterConsumerRequest{}
	mi := &file_registry_v1_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterConsumerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterConsumerRequest) ProtoMessage() {}

func (x *UnregisterConsumerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterConsumerRequest.ProtoReflect.Descriptor instead.
func (*UnregisterConsumerRequest) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{7}
}

func (x *UnregisterConsumerRequest) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

func (x *UnregisterConsumerRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *UnregisterConsumerRequest) GetProtocolType() ProtocolType {
	if x != nil {
		return x.ProtocolType
	}
	return ProtocolType_PROTOCOL_TYPE_UNSPECIFIED
}

type UnregisterConsumerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterConsumerResponse) Reset() {
	*x = UnregisterConsumerResponse{}
	mi := &file_registry_v1_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterConsumerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterConsumerResponse) ProtoMessage() {}

func (x *UnregisterConsumerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterConsumerResponse.ProtoReflect.Descriptor instead.
func (*UnregisterConsumerResponse) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{8}
}

type GetGrpcViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGrpcViewRequest) Reset() {
	*x = GetGrpcViewRequest{}
	mi := &file_registry_v1_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGrpcViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGrpcViewRequest) ProtoMessage() {}

func (x *GetGrpcViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGrpcViewRequest.ProtoReflect.Descriptor instead.
func (*GetGrpcViewRequest) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{9}
}

func (x *GetGrpcViewRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type GetGrpcViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Services      []*GrpcServiceView     `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGrpcViewResponse) Reset() {
	*x = GetGrpcViewResponse{}
	mi := &file_registry_v1_registry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGrpcViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGrpcViewResponse) ProtoMessage() {}

func (x *GetGrpcViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGrpcViewResponse.ProtoReflect.Descriptor instead.
func (*GetGrpcViewResponse) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{10}
}

func (x *GetGrpcViewResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetGrpcViewResponse) GetServices() []*GrpcServiceView {
	if x != nil {
		return x.Services
	}
	return nil
}

type GrpcServiceView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Methods       []*GrpcMethodView      `protobuf:"bytes,2,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcServiceView) Reset() {
	*x = GrpcServiceView{}
	mi := &file_registry_v1_registry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcServiceView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcServiceView) ProtoMessage() {}

func (x *GrpcServiceView) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcServiceView.ProtoReflect.Descriptor instead.
func (*GrpcServiceView) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{11}
}

func (x *GrpcServiceView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GrpcServiceView) GetMethods() []*GrpcMethodView {
	if x != nil {
		return x.Methods
	}
	return nil
}

type GrpcMethodView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Input         *GrpcMessageView       `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Output        *GrpcMessageView       `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Consumers     []string               `protobuf:"bytes,4,rep,name=consumers,proto3" json:"consumers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcMethodView) Reset() {
	*x = GrpcMethodView{}
	mi := &file_registry_v1_registry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcMethodView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcMethodView) ProtoMessage() {}

func (x *GrpcMethodView) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcMethodView.ProtoReflect.Descriptor instead.
func (*GrpcMethodView) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{12}
}

func (x *GrpcMethodView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GrpcMethodView) GetInput() *GrpcMessageView {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *GrpcMethodView) GetOutput() *GrpcMessageView {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *GrpcMethodView) GetConsumers() []string {
	if x != nil {
		return x.Consumers
	}
	return nil
}

type GrpcMessageView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fields        []*GrpcFieldView       `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcMessageView) Reset() {
	*x = GrpcMessageView{}
	mi := &file_registry_v1_registry_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcMessageView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcMessageView) ProtoMessage() {}

func (x *GrpcMessageView) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcMessageView.ProtoReflect.Descriptor instead.
func (*GrpcMessageView) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{13}
}

func (x *GrpcMessageView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GrpcMessageView) GetFields() []*GrpcFieldView {
	if x != nil {
		return x.Fields
	}
	return nil
}

type GrpcFieldView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Number        uint32                 `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	Consumers     []string               `protobuf:"bytes,4,rep,name=consumers,proto3" json:"consumers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcFieldView) Reset() {
	*x = GrpcFieldView{}
	mi := &file_registry_v1_registry_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcFieldView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcFieldView) ProtoMessage() {}

func (x *GrpcFieldView) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcFieldView.ProtoReflect.Descriptor instead.
func (*GrpcFieldView) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{14}
}

func (x *GrpcFieldView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GrpcFieldView) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GrpcFieldView) GetNumber() uint32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *GrpcFieldView) GetConsumers() []string {
	if x != nil {
		return x.Consumers
	}
	return nil
}

type ListServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_registry_v1_registry_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{15}
}

type ListServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceInfo         `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_registry_v1_registry_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{16}
}

func (x *ListServicesResponse) GetServices() []*ServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_registry_v1_registry_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{17}
}

func (x *ServiceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListProtocolVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ProtocolType  ProtocolType           `protobuf:"varint,2,opt,name=protocol_type,json=protocolType,proto3,enum=registry.v1.ProtocolType" json:"protocol_type,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProtocolVersionsRequest) Reset() {
	*x = ListProtocolVersionsRequest{}
	mi := &file_registry_v1_registry_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProtocolVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProtocolVersionsRequest) ProtoMessage() {}

func (x *ListProtocolVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProtocolVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListProtocolVersionsRequest) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{18}
}

func (x *ListProtocolVersionsRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ListProtocolVersionsRequest) GetProtocolType() ProtocolType {
	if x != nil {
		return x.ProtocolType
	}
	return ProtocolType_PROTOCOL_TYPE_UNSPECIFIED
}

func (x *ListProtocolVersionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProtocolVersionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ProtocolVersionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionNumber int32                  `protobuf:"varint,1,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	ContentHash   string                 `protobuf:"bytes,2,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	FileCount     int32                  `protobuf:"varint,3,opt,name=file_count,json=fileCount,proto3" json:"file_count,omitempty"`
	PublishedAt   string                 `protobuf:"bytes,4,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"` // ISO 8601 UTC timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolVersionInfo) Reset() {
	*x = ProtocolVersionInfo{}
	mi := &file_registry_v1_registry_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolVersionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolVersionInfo) ProtoMessage() {}

func (x *ProtocolVersionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolVersionInfo.ProtoReflect.Descriptor instead.
func (*ProtocolVersionInfo) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{19}
}

func (x *ProtocolVersionInfo) GetVersionNumber() int32 {
	if x != nil {
		return x.VersionNumber
	}
	return 0
}

func (x *ProtocolVersionInfo) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *ProtocolVersionInfo) GetFileCount() int32 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

func (x *ProtocolVersionInfo) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

type ListProtocolVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ProtocolType  ProtocolType           `protobuf:"varint,2,opt,name=protocol_type,json=protocolType,proto3,enum=registry.v1.ProtocolType" json:"protocol_type,omitempty"`
	Versions      []*ProtocolVersionInfo `protobuf:"bytes,3,rep,name=versions,proto3" json:"versions,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProtocolVersionsResponse) Reset() {
	*x = ListProtocolVersionsResponse{}
	mi := &file_registry_v1_registry_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProtocolVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProtocolVersionsResponse) ProtoMessage() {}

func (x *ListProtocolVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_registry_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProtocolVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListProtocolVersionsResponse) Descriptor() ([]byte, []int) {
	return file_registry_v1_registry_proto_rawDescGZIP(), []int{20}
}

func (x *ListProtocolVersionsResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ListProtocolVersionsResponse) GetProtocolType() ProtocolType {
	if x != nil {
		return x.ProtocolType
	}
	return ProtocolType_PROTOCOL_TYPE_UNSPECIFIED
}

func (x *ListProtocolVersionsResponse) GetVersions() []*ProtocolVersionInfo {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *ListProtocolVersionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_registry_v1_registry_proto protoreflect.FileDescriptor

const file_registry_v1_registry_proto_rawDesc = "" +
	"\n" +
	"\x1aregistry/v1/registry.proto\x12\vregistry.v1\"9\n" +
	"\tProtoFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"\xd0\x01\n" +
	"\x16PublishProtocolRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12>\n" +
	"\rprotocol_type\x18\x03 \x01(\x0e2\x19.registry.v1.ProtocolTypeR\fprotocolType\x12,\n" +
	"\x05files\x18\x04 \x03(\v2\x16.registry.v1.ProtoFileR\x05files\x12\x1f\n" +
	"\ventry_point\x18\x05 \x01(\tR\n" +
	"entryPointJ\x04\b\x02\x10\x03\"S\n" +
	"\x17PublishProtocolResponse\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x15\n" +
	"\x06is_new\x18\x02 \x01(\bR\x05isNew\"w\n" +
	"\x12GetProtocolRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12>\n" +
	"\rprotocol_type\x18\x02 \x01(\x0e2\x19.registry.v1.ProtocolTypeR\fprotocolType\"\xcd\x01\n" +
	"\x13GetProtocolResponse\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12>\n" +
	"\rprotocol_type\x18\x02 \x01(\x0e2\x19.registry.v1.ProtocolTypeR\fprotocolType\x12,\n" +
	"\x05files\x18\x04 \x03(\v2\x16.registry.v1.ProtoFileR\x05files\x12\x1f\n" +
	"\ventry_point\x18\x05 \x01(\tR\n" +
	"entryPointJ\x04\b\x03\x10\x04\"\xf4\x01\n" +
	"\x17RegisterConsumerRequest\x12#\n" +
	"\rconsumer_name\x18\x01 \x01(\tR\fconsumerName\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x12>\n" +
	"\rprotocol_type\x18\x03 \x01(\x0e2\x19.registry.v1.ProtocolTypeR\fprotocolType\x12,\n" +
	"\x05files\x18\x05 \x03(\v2\x16.registry.v1.ProtoFileR\x05files\x12\x1f\n" +
	"\ventry_point\x18\x06 \x01(\tR\n" +
	"entryPointJ\x04\b\x04\x10\x05\"w\n" +
	"\x18RegisterConsumerResponse\x12#\n" +
	"\rconsumer_name\x18\x01 \x01(\tR\fconsumerName\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x12\x15\n" +
	"\x06is_new\x18\x03 \x01(\bR\x05isNew\"\xa1\x01\n" +
	"\x19UnregisterConsumerRequest\x12#\n" +
	"\rconsumer_name\x18\x01 \x01(\tR\fconsumerName\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x12>\n" +
	"\rprotocol_type\x18\x03 \x01(\x0e2\x19.registry.v1.ProtocolTypeR\fprotocolType\"\x1c\n" +
	"\x1aUnregisterConsumerResponse\"7\n" +
	"\x12GetGrpcViewRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"r\n" +
	"\x13GetGrpcViewResponse\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x128\n" +
	"\bservices\x18\x02 \x03(\v2\x1c.registry.v1.GrpcServiceViewR\bservices\"\\\n" +
	"\x0fGrpcServiceView\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\amethods\x18\x02 \x03(\v2\x1b.registry.v1.GrpcMethodViewR\amethods\"\xac\x01\n" +
	"\x0eGrpcMethodView\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x05input\x18\x02 \x01(\v2\x1c.registry.v1.GrpcMessageViewR\x05input\x124\n" +
	"\x06output\x18\x03 \x01(\v2\x1c.registry.v1.GrpcMessageViewR\x06output\x12\x1c\n" +
	"\tconsumers\x18\x04 \x03(\tR\tconsumers\"Y\n" +
	"\x0fGrpcMessageView\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x06fields\x18\x02 \x03(\v2\x1a.registry.v1.GrpcFieldViewR\x06fields\"m\n" +
	"\rGrpcFieldView\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06number\x18\x03 \x01(\rR\x06number\x12\x1c\n" +
	"\tconsumers\x18\x04 \x03(\tR\tconsumers\"\x15\n" +
	"\x13ListServicesRequest\"L\n" +
	"\x14ListServicesResponse\x124\n" +
	"\bservices\x18\x01 \x03(\v2\x18.registry.v1.ServiceInfoR\bservices\"1\n" +
	"\vServiceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xb5\x01\n" +
	"\x1bListProtocolVersionsRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12>\n" +
	"\rprotocol_type\x18\x02 \x01(\x0e2\x19.registry.v1.ProtocolTypeR\fprotocolType\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\xa1\x01\n" +
	"\x13ProtocolVersionInfo\x12%\n" +
	"\x0eversion_number\x18\x01 \x01(\x05R\rversionNumber\x12!\n" +
	"\fcontent_hash\x18\x02 \x01(\tR\vcontentHash\x12\x1d\n" +
	"\n" +
	"file_count\x18\x03 \x01(\x05R\tfileCount\x12!\n" +
	"\fpublished_at\x18\x04 \x01(\tR\vpublishedAt\"\xd5\x01\n" +
	"\x1cListProtocolVersionsResponse\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12>\n" +
	"\rprotocol_type\x18\x02 \x01(\x0e2\x19.registry.v1.ProtocolTypeR\fprotocolType\x12<\n" +
	"\bversions\x18\x03 \x03(\v2 .registry.v1.ProtocolVersionInfoR\bversions\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total*`\n" +
	"\fProtocolType\x12\x1d\n" +
	"\x19PROTOCOL_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PROTOCOL_TYPE_GRPC\x10\x01\x12\x19\n" +
	"\x15PROTOCOL_TYPE_OPENAPI\x10\x022\x9e\x05\n" +
	"\x10ProtocolRegistry\x12\\\n" +
	"\x0fPublishProtocol\x12#.registry.v1.PublishProtocolRequest\x1a$.registry.v1.PublishProtocolResponse\x12P\n" +
	"\vGetProtocol\x12\x1f.registry.v1.GetProtocolRequest\x1a .registry.v1.GetProtocolResponse\x12_\n" +
	"\x10RegisterConsumer\x12$.registry.v1.RegisterConsumerRequest\x1a%.registry.v1.RegisterConsumerResponse\x12e\n" +
	"\x12UnregisterConsumer\x12&.registry.v1.UnregisterConsumerRequest\x1a'.registry.v1.UnregisterConsumerResponse\x12P\n" +
	"\vGetGrpcView\x12\x1f.registry.v1.GetGrpcViewRequest\x1a .registry.v1.GetGrpcViewResponse\x12S\n" +
	"\fListServices\x12 .registry.v1.ListServicesRequest\x1a!.registry.v1.ListServicesResponse\x12k\n" +
	"\x14ListProtocolVersions\x12(.registry.v1.ListProtocolVersionsRequest\x1a).registry.v1.ListProtocolVersionsResponseB\xaf\x01\n" +
	"\x0fcom.registry.v1B\rRegistryProtoP\x01Z@github.com/user/protocol_registry/pkg/api/registry/v1;registryv1\xa2\x02\x03RXX\xaa\x02\vRegistry.V1\xca\x02\vRegistry\\V1\xe2\x02\x17Registry\\V1\\GPBMetadata\xea\x02\fRegistry::V1b\x06proto3"

var (
	file_registry_v1_registry_proto_rawDescOnce sync.Once
	file_registry_v1_registry_proto_rawDescData []byte
)

func file_registry_v1_registry_proto_rawDescGZIP() []byte {
	file_registry_v1_registry_proto_rawDescOnce.Do(func() {
		file_registry_v1_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_registry_v1_registry_proto_rawDesc), len(file_registry_v1_registry_proto_rawDesc)))
	})
	return file_registry_v1_registry_proto_rawDescData
}

var file_registry_v1_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_registry_v1_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_registry_v1_registry_proto_goTypes = []any{
	(ProtocolType)(0),                    // 0: registry.v1.ProtocolType
	(*ProtoFile)(nil),                    // 1: registry.v1.ProtoFile
	(*PublishProtocolRequest)(nil),       // 2: registry.v1.PublishProtocolRequest
	(*PublishProtocolResponse)(nil),      // 3: registry.v1.PublishProtocolResponse
	(*GetProtocolRequest)(nil),           // 4: registry.v1.GetProtocolRequest
	(*GetProtocolResponse)(nil),          // 5: registry.v1.GetProtocolResponse
	(*RegisterConsumerRequest)(nil),      // 6: registry.v1.RegisterConsumerRequest
	(*RegisterConsumerResponse)(nil),     // 7: registry.v1.RegisterConsumerResponse
	(*UnregisterConsumerRequest)(nil),    // 8: registry.v1.UnregisterConsumerRequest
	(*UnregisterConsumerResponse)(nil),   // 9: registry.v1.UnregisterConsumerResponse
	(*GetGrpcViewRequest)(nil),           // 10: registry.v1.GetGrpcViewRequest
	(*GetGrpcViewResponse)(nil),          // 11: registry.v1.GetGrpcViewResponse
	(*GrpcServiceView)(nil),              // 12: registry.v1.GrpcServiceView
	(*GrpcMethodView)(nil),               // 13: registry.v1.GrpcMethodView
	(*GrpcMessageView)(nil),              // 14: registry.v1.GrpcMessageView
	(*GrpcFieldView)(nil),                // 15: registry.v1.GrpcFieldView
	(*ListServicesRequest)(nil),          // 16: registry.v1.ListServicesRequest
	(*ListServicesResponse)(nil),         // 17: registry.v1.ListServicesResponse
	(*ServiceInfo)(nil),                  // 18: registry.v1.ServiceInfo
	(*ListProtocolVersionsRequest)(nil),  // 19: registry.v1.ListProtocolVersionsRequest
	(*ProtocolVersionInfo)(nil),          // 20: registry.v1.ProtocolVersionInfo
	(*ListProtocolVersionsResponse)(nil), // 21: registry.v1.ListProtocolVersionsResponse
}
var file_registry_v1_registry_proto_depIdxs = []int32{
	0,  // 0: registry.v1.PublishProtocolRequest.protocol_type:type_name -> registry.v1.ProtocolType
	1,  // 1: registry.v1.PublishProtocolRequest.files:type_name -> registry.v1.ProtoFile
	0,  // 2: registry.v1.GetProtocolRequest.protocol_type:type_name -> registry.v1.ProtocolType
	0,  // 3: registry.v1.GetProtocolResponse.protocol_type:type_name -> registry.v1.ProtocolType
	1,  // 4: registry.v1.GetProtocolResponse.files:type_name -> registry.v1.ProtoFile
	0,  // 5: registry.v1.RegisterConsumerRequest.protocol_type:type_name -> registry.v1.ProtocolType
	1,  // 6: registry.v1.RegisterConsumerRequest.files:type_name -> registry.v1.ProtoFile
	0,  // 7: registry.v1.UnregisterConsumerRequest.protocol_type:type_name -> registry.v1.ProtocolType
	12, // 8: registry.v1.GetGrpcViewResponse.services:type_name -> registry.v1.GrpcServiceView
	13, // 9: registry.v1.GrpcServiceView.methods:type_name -> registry.v1.GrpcMethodView
	14, // 10: registry.v1.GrpcMethodView.input:type_name -> registry.v1.GrpcMessageView
	14, // 11: registry.v1.GrpcMethodView.output:type_name -> registry.v1.GrpcMessageView
	15, // 12: registry.v1.GrpcMessageView.fields:type_name -> registry.v1.GrpcFieldView
	18, // 13: registry.v1.ListServicesResponse.services:type_name -> registry.v1.ServiceInfo
	0,  // 14: registry.v1.ListProtocolVersionsRequest.protocol_type:type_name -> registry.v1.ProtocolType
	0,  // 15: registry.v1.ListProtocolVersionsResponse.protocol_type:type_name -> registry.v1.ProtocolType
	20, // 16: registry.v1.ListProtocolVersionsResponse.versions:type_name -> registry.v1.ProtocolVersionInfo
	2,  // 17: registry.v1.ProtocolRegistry.PublishProtocol:input_type -> registry.v1.PublishProtocolRequest
	4,  // 18: registry.v1.ProtocolRegistry.GetProtocol:input_type -> registry.v1.GetProtocolRequest
	6,  // 19: registry.v1.ProtocolRegistry.RegisterConsumer:input_type -> registry.v1.RegisterConsumerRequest
	8,  // 20: registry.v1.ProtocolRegistry.UnregisterConsumer:input_type -> registry.v1.UnregisterConsumerRequest
	10, // 21: registry.v1.ProtocolRegistry.GetGrpcView:input_type -> registry.v1.GetGrpcViewRequest
	16, // 22: registry.v1.ProtocolRegistry.ListServices:input_type -> registry.v1.ListServicesRequest
	19, // 23: registry.v1.ProtocolRegistry.ListProtocolVersions:input_type -> registry.v1.ListProtocolVersionsRequest
	3,  // 24: registry.v1.ProtocolRegistry.PublishProtocol:output_type -> registry.v1.PublishProtocolResponse
	5,  // 25: registry.v1.ProtocolRegistry.GetProtocol:output_type -> registry.v1.GetProtocolResponse
	7,  // 26: registry.v1.ProtocolRegistry.RegisterConsumer:output_type -> registry.v1.RegisterConsumerResponse
	9,  // 27: registry.v1.ProtocolRegistry.UnregisterConsumer:output_type -> registry.v1.UnregisterConsumerResponse
	11, // 28: registry.v1.ProtocolRegistry.GetGrpcView:output_type -> registry.v1.GetGrpcViewResponse
	17, // 29: registry.v1.ProtocolRegistry.ListServices:output_type -> registry.v1.ListServicesResponse
	21, // 30: registry.v1.ProtocolRegistry.ListProtocolVersions:output_type -> registry.v1.ListProtocolVersionsResponse
	24, // [24:31] is the sub-list for method output_type
	17, // [17:24] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_registry_v1_registry_proto_init() }
func file_registry_v1_registry_proto_init() {
	if File_registry_v1_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_registry_v1_registry_proto_rawDesc), len(file_registry_v1_registry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_registry_v1_registry_proto_goTypes,
		DependencyIndexes: file_registry_v1_registry_proto_depIdxs,
		EnumInfos:         file_registry_v1_registry_proto_enumTypes,
		MessageInfos:      file_registry_v1_registry_proto_msgTypes,
	}.Build()
	File_registry_v1_registry_proto = out.File
	file_registry_v1_registry_proto_goTypes = nil
	file_registry_v1_registry_proto_depIdxs = nil
}
